# Generated by Django 4.0.3 on 2022-05-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystor', '0002_rename_sekking_price_product_striping_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='striping_price',
            new_name='salling_price',
        ),
    ]
